# To use:
# The following needs to be configured for this starter workflow to work
#   properly in production:
#   Line 27 - name: Workflow name which appears under "Workflows" in the repo's
#     Actions tab.
#   Line 51 - version: The version of MATLAB the library is saved in.
#   Line 52 - project: The name of the MATLAB project for the library to build.
#   Line 53 - required_labels: A list of runner labels required to build the
#     library other than ["self-hosted", "Windows", "matlab"]. This property is
#     not required and can be removed if the default labels are enough to build
#     the library.
#   Line 54 - timeout_minutes: Maximum time a library build job is allowed to
#     run before the job gives up.
#   Line 55 - run_cmd: Custom MATLAB command to run to build a library. This
#     input element is optional and if undefined, the default eng-vme-actions
#     MATLAB command to build a library will be ran.
#   Line 56 - status_check: True to use this workflow as a Status Check. This
#     input is optional and defaults to `true` if undefined.
#
# Notes:
# 1. Save this file in a ".github/workflows" directory in the root of the
#   repository.
# 2. Make sure to change this file extension to yml and give it a good name.
# 3. Refer to https://docs.github.com/en/actions/learn-github-actions for more
#   information.

name: "" # Example: "Build Library"
on:
  # Manually trigger this workflow
  workflow_dispatch:
    # Prompts shown when manually triggering this workflow
    inputs:
      override_push:
        description: "Select this option to force push an output branch even when the source is not the default branch."
        type: boolean
        default: true
  # Run when pushes are detected to branches except those defined below
  push:
    branches-ignore:
      - "**dist"
      - "**Dist"

jobs:
  BuildLibrary:
    name: Build Library
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    uses: vermeer-corp/eng-vme-actions/.github/workflows/build_library_reusable.yml@v5
    with:
      version: "" # Example: "2023a"
      project: "" # Example: "Vermeer_Base_Library"
      required_labels: "" # Example: "'qt', 'matlab-coder'"
      timeout_minutes: "" # Example: "15"
      run_cmd: "" # Example: "addpath(fullfile(pwd)); BuildLibrary('VME3_OS_Library');"
      status_check: "" # Example: "true"
      override_push: ${{ inputs.override_push }}
    secrets:
      read_token: ${{ secrets.VPACKAGE_ACCESS_PRIV_KEY }}
      write_token: ${{ secrets.GITHUB_TOKEN }}
