# To use:
# The following needs to be configured for this starter workflow to work
#   properly in production:
#   Line 26 - name: Workflow name which appears under "Workflows" in the repo's
#     Actions tab.
#   Line 35 - branches: Name of the base branch for PRs that will trigger this
#     workflow. Normally this is just the default branch, but more can be
#     defined.
#   Line 39 - branches: Name of the default branch, or target branch(es) for
#     pull requests, for this repository.
#   Line 50 - status_check: True to use this workflow as a Status Check. This
#     input is optional and defaults to `true` if undefined.
#
# Notes:
# 1. Save this file in a ".github/workflows" directory in the root of the
#   repository.
# 2. Make sure to change this file extension to yml and give it a good name.
# 3. To deploy documentation in a repository to TLDR/TechDocs, there must exist
#   a valid "mkdocs.yml" in the repository's root and a valid
#   "tldr/catalog-info.yaml" file.
# 4. Refer to https://tldr.vermeer.com/docs/default/Component/pt-backstage/ for
#   more information on IT's TLDR and TechDocs system.
# 5. Refer to https://docs.github.com/en/actions/learn-github-actions for more
#   information about GitHub Actions.

name: "" # Example: "Deploy To TechDocs"
on:
  # Manually trigger this workflow
  workflow_dispatch:
  # Run on PR open, reopen, synchronize, or when marked "ready for review" when
  # the target is the defined branch(es)
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - "" # Example: "main"
  # Trigger on pushes to the defined branch(es)
  push:
    branches:
      - "" # Example: "main"

jobs:
  DeployToTechDocs:
    name: "Deploy To TechDocs"
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    uses: vermeer-corp/eng-vme-actions/.github/workflows/deploy_to_tech_docs_reusable.yml@v5
    secrets: inherit
    with:
      status_check: "" # Example: "true"
