# To use:
# The following needs to be configured for this starter workflow to work
#   properly in production:
#   Line 37 - name: Workflow name which appears under "Workflows" in the repo's
#     Actions tab.
#   Line 65 - version: The version of MATLAB the project is saved in.
#   Line 66 - root_project: The name of the MATLAB project containing the
#     project to export.
#   Line 67 - export_project: Name of the MATLAB sub-project of `root_project`
#     to export.
#   Line 68 - required_labels: A list of runner labels required to export the
#     project other than ["self-hosted", "Windows", "matlab"]. This property is
#     not required and can be removed if the default labels are enough to export
#     the project.
#   Line 69 - timeout_minutes: Maximum time a project export job is allowed to
#     run before the job gives up. Defaults to `10` if undefined.
#   Line 70 - run_cmd: Custom MATLAB command to run to export a Simulink
#     project. This input element is optional and if undefined, the default
#     eng-vme-actions MATLAB command to export a MATLAB project will be ran.
#   Line 71 - status_check: True to use this workflow as a Status Check. This
#     input is optional and defaults to `true` if undefined.
#   Line 72: generate_docs: True to generate formatted library help
#     documentation before exporting the project.
#   Line 73: export_profile: Default name of the profile to export the project
#     with. See
#     https://www.mathworks.com/help/matlab/ref/matlab.project.project.export.html#mw_4da5d920-ce4a-4e92-bdb8-65485c22c9bb.
#
# Notes:
# 1. This workflow will fail if exporting a project not saved in MATLAB 2023a or
#   later.
# 2. Save this file in a ".github/workflows" directory in the root of the
#   repository.
# 3. Make sure to change this file extension to yml and give it a good name.
# 4. Refer to https://docs.github.com/en/actions/learn-github-actions for more
#   information.

name: "" # Example: "Export Simulink Project"
on:
  # Manually trigger this workflow
  workflow_dispatch:
    # Prompts shown when manually triggering this workflow
    inputs:
      override_push:
        description: "Push to an output branch even when the source is not the default branch."
        type: boolean
        default: true
      export_profile:
        description: "The name of the profile to export the project with. If blank, defaults to the workflow default."
        type: string
  # Run when pushes are detected to branches except those defined below
  push:
    branches-ignore:
      - "**dist"
      - "**Dist"

jobs:
  ExportSimulinkProject:
    name: Export Simulink Project
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    uses: vermeer-corp/eng-vme-actions/.github/workflows/export_simulink_project_reusable.yml@v5
    secrets: inherit
    with:
      version: "" # Example: "2023a"
      root_project: "" # Example: "eng_vme2_maintenancereminder_library" or "./eng_vme2_maintenancereminder_library.prj"
      export_project: "" # Example: "Vermeer_MaintenanceReminder_Library" or "Source/Vermeer_MaintenanceReminder_Library.prj"
      required_labels: "" # Example: "qt, matlab-coder"
      timeout_minutes: "" # Example: "15"
      run_cmd: "" # Example: "addpath(fullfile(pwd)); ExportSimulinkProject('VME3_OS_Library');"
      status_check: "" # Example: "true"
      generate_docs: "" # Example: "true"
      export_profile: ${{ inputs.export_profile || '' }} # Example: 'dist'
      override_push: ${{ inputs.override_push }}
