name: GitLeaks Secret Scan

# It's recommended to leave the triggers like this
# to reduce workflows running on all branches. To
# catch commited secrets sooner, please install a
# pre-commit hook as shown at:
# https://github.com/zricethezav/gitleaks#pre-commit
on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: "0"

      - name: Use Vermeer Definitions # forked from official repo with exceptions for false positives
        run: mkdir security; wget -P security/ https://raw.githubusercontent.com/vermeer-corp/gitleaks/master/config/gitleaks.toml

      - name: Run GitLeaks Scan
        id: gitleaks
        uses: DariuszPorowski/github-action-gitleaks@a027585cb1f2780aa441f20f4d0aabf8b1a0d90e # v2
        with:
          config: security/gitleaks.toml
