# To use:
# The following needs to be configured for this starter workflow to work
#   properly in production:
#   Line 18 - name: Workflow name which appears under "Workflows" in the repo's
#     Actions tab.
#   Line 25 - branches: Name of the base branch for PRs that will trigger this
#     workflow. Normally this is just the default branch, but more can be
#     defined.
#   Line 29 - name: Job name which appears under the Workflow.
#
# Notes:
# 1. Save this file in a ".github/workflows" directory in the root of the
#   repository.
# 2. Make sure to change this file extension to yml and give it a good name.
# 3. Refer to https://docs.github.com/en/actions/learn-github-actions for more
#   information about GitHub Actions.

name: "" # Example: "Prettier Code Format"
on:
  # Manually trigger this workflow
  workflow_dispatch:
  # Run on PR open, reopen, or synchronize when the target is the defined branch
  pull_request:
    branches:
      - "" # Example: "main"

jobs:
  FormatCode:
    name: "" # Example: "Format Code"
    runs-on: [self-hosted, ubuntu]
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Prettier code format
        uses: vermeer-corp/eng-vme-actions/PrettierCodeFormat@v5
