# To use:
# The following needs to be configured for this starter workflow to work
#   properly in production:
#   Line 32 - name: Workflow name which appears under "Workflows" in the repo's
#     Actions tab.
#   Line 45 - base_branch: Name of the default branch to compare changed files
#     to.
#   Line 50 - branches: Name of the default branch, or target branch(es) for
#     pull requests, for this repository.
#   Line 60 - version: The version of MATLAB the models are saved in.
#   Line 61 - project: The name of the MATLAB project to run tests for.
#   Line 62 - required_labels: A list of runner labels required to run project
#     tests other than ["self-hosted", "Windows", "matlab"]. This property is
#     not required and can be removed if the default labels are enough to run
#     project tests.
#   Line 63 - timeout_minutes: Maximum time a run tests job is allowed to run
#     before the job gives up.
#   Line 64 - run_cmd: Custom MATLAB command to run project tests. This input
#     element is optional and if undefined, the default eng-vme-actions MATLAB
#     command to run project tests will be ran.
#   Line 65 - status_check: True to use this workflow as a Status Check. This
#     input is optional and defaults to `true` if undefined.
#
# Notes:
# 1. Save this file in a ".github/workflows" directory in the root of the
#   repository.
# 2. Make sure to change this file extension to "yml" and give it a good name.
# 3. All defined paths are relative to the root of the repository.
# 4. Refer to https://docs.github.com/en/actions/learn-github-actions for more
#   information.

name: "" # Example: "Run Project Tests"
on:
  # Manually trigger this workflow
  workflow_dispatch:
    # Prompts shown when manually triggering this workflow
    inputs:
      test_all:
        description: "Run all tests regardless of files changed."
        type: boolean
        default: true
      base_branch:
        description: "If `test_all` is false, name of the branch to compare files to. Typically, this is the repository's default branch. If blank, this workflow will compare the HEAD commit of the branch being executed to the previous commit of the same branch."
        type: string
        default: "" # Example: "main"
  # Run on PR open, reopen, synchronize, or when marked "ready for review" when the target is the defined branch
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - "" # Example: "main"

jobs:
  RunProjectTests:
    name: Run Project Tests
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    uses: vermeer-corp/eng-vme-actions/.github/workflows/run_project_tests_reusable.yml@v5
    with:
      version: "" # Example: "2023a"
      project: "" # Example: "CTX_Software.prj" or "CTX_Software"
      required_labels: "" # Example: "'qt', 'matlab-coder'"
      timeout_minutes: "" # Example: "15"
      run_cmd: "" # Example: "openProject(pwd); compile_cmds_runtests"
      status_check: "" # Example: "true"
      test_all: ${{ inputs.test_all }}
      base_branch: ${{ inputs.base_branch }}
    secrets:
      read_token: ${{ secrets.VPACKAGE_ACCESS_PRIV_KEY }}
